/**
 * Postgres connection module (postgres-js + Drizzle).
 *
 * `getPostgresClient(env)` lazily constructs a single postgres-js client
 * per process (module-level cache) — a Workers isolate is reused across
 * requests, so a fresh client per request would leak connections instead
 * of pooling them. `buildDrizzle(env)` wires that client into Drizzle.
 *
 * The standalone agent runtime (`agent-runtime/`, a plain Bun process) has
 * no network path to Supabase and no `SUPABASE_DB_URL`; it is detected via
 * `isStandaloneRuntime(env)` (see `worker/utils/runtimeMode.ts`, the same
 * seam Phase 1 used for the D1 no-op) and always gets `noopPg`'s stand-in
 * instead — see `worker/database/noopPg.ts`.
 */

import postgres from 'postgres';
import { drizzle } from 'drizzle-orm/postgres-js';
import type { PostgresJsDatabase } from 'drizzle-orm/postgres-js';
import * as schema from './schema';
import { isStandaloneRuntime } from '../utils/runtimeMode';
import { createNoopPostgres } from './noopPg';

/** Supabase connection pooler default; keeps per-isolate connection count bounded. */
const MAX_CONNECTIONS = 5;

let cachedClient: postgres.Sql | undefined;

/**
 * Reads `SUPABASE_DB_URL` without widening the generated `Env` type.
 *
 * `worker-configuration.d.ts` is generated by `wrangler types` from
 * `wrangler.jsonc` bindings/vars and must not be hand-edited (see
 * `worker/utils/runtimeMode.ts` for the precedent: `RUNTIME_MODE` is read
 * the same way rather than declared on `Env`). `SUPABASE_DB_URL` is a
 * plain secret var, not a Cloudflare binding, so it is read through this
 * indexed cast instead.
 */
function getSupabaseDbUrl(env: Env): string {
    const url = (env as unknown as Record<string, unknown>).SUPABASE_DB_URL;
    if (typeof url !== 'string' || url.length === 0) {
        throw new Error('SUPABASE_DB_URL is not configured');
    }
    return url;
}

/**
 * Lazily constructs (and caches) the postgres-js client for the current
 * process. Never called on the standalone runtime path — see `buildDrizzle`.
 * `prepare: false` is required for Supabase's transaction pooler (pgbouncer
 * in transaction mode does not support server-side prepared statements).
 */
export function getPostgresClient(env: Env): postgres.Sql {
    if (!cachedClient) {
        cachedClient = postgres(getSupabaseDbUrl(env), {
            prepare: false,
            ssl: 'require',
            max: MAX_CONNECTIONS,
        });
    }
    return cachedClient;
}

/**
 * Builds the Drizzle database instance for the current runtime:
 * standalone agent runtime -> no-op client (never opens a real connection);
 * Workers runtime -> real postgres-js client against Supabase.
 */
export function buildDrizzle(env: Env): PostgresJsDatabase<typeof schema> {
    if (isStandaloneRuntime(env)) {
        return drizzle(createNoopPostgres(), { schema });
    }
    return drizzle(getPostgresClient(env), { schema });
}
